# Generated by Django 5.0.4 on 2026-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash la livrare'), ('card', 'Card (simulat)')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('posta_romana', 'Poșta Română (15 RON)'), ('fan_courier', 'Fan Courier (20 RON)'), ('cargus', 'Cargus (18 RON)'), ('dpd', 'DPD (17 RON)'), ('ridicare', 'Ridicare personală (gratuit)')], default='posta_romana', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
